language: python
python:
  - 2.7

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - "git submodule update --init"
  - "pip install flake8"
  - "pip install -r requirements.txt"

before_script: "flake8 . --ignore=E501"

script: py.test -n 4 -v -r fsxX --baseurl=https://www.allizom.org --driver=firefox --destructive -m "not credentials"

notifications:
  email:
  - webqa-ci@mozilla.org
